// const { AI_PROVIDER } = require("../../config/env");
// const ollamaProvider = require("./ollamaProvider");
// const grokProvider = require("./grokProvider");
// const geminiProvider = require("./geminiProvider");
// const {
//   buildEvaluationPrompt,
//   buildFinalReportPrompt,
//   buildPlacementAnalysisPrompt,
//   buildResumeParsePrompt,
//   buildResumeVsInterviewPrompt,
// } = require("../../prompts/promptBuilder");

// const PROVIDERS = {
//   ollama: ollamaProvider,
//   grok: grokProvider,
//   gemini: geminiProvider,
// };

// function getProvider() {
//   const provider = PROVIDERS[AI_PROVIDER];
//   if (!provider) {
//     throw new Error(`Unknown AI_PROVIDER "${AI_PROVIDER}". Use ollama | grok | gemini.`);
//   }
//   return provider;
// }

// function stripJsonFences(text) {
//   return text.replace(/```json|```/g, "").trim();
// }

// function safeParseJSON(text, fallback) {
//   try {
//     return JSON.parse(stripJsonFences(text));
//   } catch {
//     return fallback;
//   }
// }

// function score(value, fallback = 0) {
//   const numeric = Number(value);
//   return Number.isFinite(numeric) ? Math.max(0, Math.min(100, Math.round(numeric))) : fallback;
// }

// function stringList(value) {
//   return Array.isArray(value) ? value.filter((item) => typeof item === "string").map((item) => item.trim()).filter(Boolean) : [];
// }

// function normalizeEvaluation(value) {
//   return {
//     correctness: score(value?.correctness, 50),
//     clarity: score(value?.clarity, 50),
//     confidence: score(value?.confidence, 50),
//     notes: typeof value?.notes === "string" ? value.notes.trim() : "",
//   };
// }

// function normalizeReport(value) {
//   return {
//     overall: score(value?.overall, 50),
//     technical: score(value?.technical, 50),
//     communication: score(value?.communication, 50),
//     confidence: score(value?.confidence, 50),
//     problemSolving: score(value?.problemSolving, 50),
//     coding: score(value?.coding, 0),
//     strengths: stringList(value?.strengths),
//     weaknesses: stringList(value?.weaknesses),
//     suggestions: stringList(value?.suggestions),
//     quotedMoments: Array.isArray(value?.quotedMoments) ? value.quotedMoments.filter((item) => item && typeof item.quote === "string") : [],
//     summary: typeof value?.summary === "string" ? value.summary.trim() : "",
//   };
// }

// /**
//  * The rest of the application must ONLY talk to this facade -
//  * never to a provider file directly. Swapping AI_PROVIDER never
//  * requires touching business logic elsewhere in the app.
//  */
// const aiService = {
//   currentProvider: () => AI_PROVIDER,

//   /** Evaluates a single answer, returning correctness/clarity/confidence + notes. */
//   async evaluateAnswer({ interview, question, answer }) {
//     const prompt = buildEvaluationPrompt({ interview, question, answer });
//     const provider = getProvider();
//     const text = await provider.complete([{ role: "user", content: prompt }]);
//     return normalizeEvaluation(safeParseJSON(text, {
//       correctness: 50,
//       clarity: 50,
//       confidence: 50,
//       notes: "Automated evaluation unavailable - default score applied.",
//     }));
//   },

//   /** Generates short inline feedback/follow-up commentary (used for live chat nudges). */
//   async generateFeedback({ interview, transcript }) {
//     const provider = getProvider();
//     const systemPrompt = `You are an interviewer for a ${interview.category} interview. Give one short (1-2 sentence) reaction to the candidate's last answer before the next question is asked.`;
//     const messages = [
//       { role: "system", content: systemPrompt },
//       ...transcript.map((t) => ({
//         role: t.role === "ai" ? "assistant" : "user",
//         content: t.content,
//       })),
//     ];
//     return provider.complete(messages);
//   },

//   /** Generates the final structured report for a completed interview. */
//   async generateFinalReport({ interview, transcript, responses }) {
//     const prompt = buildFinalReportPrompt({ interview, transcript, responses });
//     const provider = getProvider();
//     const text = await provider.complete([{ role: "user", content: prompt }]);
//     return normalizeReport(safeParseJSON(text, {
//       overall: 50,
//       technical: 50,
//       communication: 50,
//       confidence: 50,
//       problemSolving: 50,
//       coding: 0,
//       strengths: [],
//       weaknesses: [],
//       suggestions: ["Automated report generation failed - please retry."],
//       quotedMoments: [],
//       summary: "Report could not be generated by the AI provider.",
//     }));
//   },

//   /** Combines multiple category reports into an overall placement analysis. */
//   async generatePlacementAnalysis({ readinessScore, readinessLevel, categoryReports }) {
//     const prompt = buildPlacementAnalysisPrompt({ readinessScore, readinessLevel, categoryReports });
//     const provider = getProvider();
//     const text = await provider.complete([{ role: "user", content: prompt }]);
//     return safeParseJSON(text, {
//       strengths: [],
//       weaknesses: [],
//       consistentSkills: [],
//       improvementSkills: [],
//       improvementPriority: ["Automated placement analysis unavailable - please retry."],
//       careerSummary: "AI analysis could not be generated.",
//       finalRecommendation: "Complete more interviews and retry.",
//     });
//   },

//   /** Parses raw resume text into structured skills/projects/experience. */
//   async parseResume({ resumeText }) {
//     const prompt = buildResumeParsePrompt({ resumeText });
//     const provider = getProvider();
//     const text = await provider.complete([{ role: "user", content: prompt }]);
//     return safeParseJSON(text, {
//       skills: [],
//       programmingLanguages: [],
//       frameworks: [],
//       databases: [],
//       coreCsSubjects: [],
//       projects: [],
//       experience: [],
//       certifications: [],
//     });
//   },

//   /** Compares resume claims against interview performance. */
//   async analyzeResumeVsInterview({ resumeProfile, categoryReports }) {
//     const prompt = buildResumeVsInterviewPrompt({ resumeProfile, categoryReports });
//     const provider = getProvider();
//     const text = await provider.complete([{ role: "user", content: prompt }]);
//     return safeParseJSON(text, {
//       matchScore: 0,
//       verifiedSkills: [],
//       unverifiedSkills: [],
//       improvementSkills: [],
//       missingAreas: [],
//       suggestions: ["Automated resume analysis unavailable - please retry."],
//       summary: "AI analysis could not be generated.",
//     });
//   },
// };

// module.exports = aiService;
// const { AI_PROVIDER } = require("../../config/env");

// const ollamaProvider = require("./ollamaProvider");
// const groqProvider = require("./grokProvider");
// const geminiProvider = require("./geminiProvider");

// const {
//   buildEvaluationPrompt,
//   buildFinalReportPrompt,
//   buildPlacementAnalysisPrompt,
//   buildResumeParsePrompt,
//   buildResumeVsInterviewPrompt,
// } = require("../../prompts/promptBuilder");

// // ============================================================
// // AI PROVIDERS
// // ============================================================

// const PROVIDERS = {
//   ollama: ollamaProvider,
//   groq: groqProvider,
//   gemini: geminiProvider,
// };

// // ============================================================
// // GET ACTIVE PROVIDER
// // ============================================================

// function getProvider() {
//   const provider = PROVIDERS[AI_PROVIDER];

//   if (!provider) {
//     throw new Error(
//       `Unknown AI_PROVIDER "${AI_PROVIDER}". Use ollama | groq | gemini.`
//     );
//   }

//   return provider;
// }

// // ============================================================
// // JSON HELPERS
// // ============================================================

// function stripJsonFences(text) {
//   if (typeof text !== "string") {
//     return "";
//   }

//   return text
//     .replace(/```json/gi, "")
//     .replace(/```/g, "")
//     .trim();
// }

// function safeParseJSON(text, fallback) {
//   try {
//     return JSON.parse(stripJsonFences(text));
//   } catch {
//     return fallback;
//   }
// }

// // ============================================================
// // NORMALIZATION HELPERS
// // ============================================================

// function score(value, fallback = 0) {
//   const numeric = Number(value);

//   return Number.isFinite(numeric)
//     ? Math.max(0, Math.min(100, Math.round(numeric)))
//     : fallback;
// }

// function stringList(value) {
//   return Array.isArray(value)
//     ? value
//         .filter((item) => typeof item === "string")
//         .map((item) => item.trim())
//         .filter(Boolean)
//     : [];
// }

// // ============================================================
// // EVALUATION NORMALIZER
// // ============================================================

// function normalizeEvaluation(value) {
//   return {
//     correctness: score(value?.correctness, 50),
//     clarity: score(value?.clarity, 50),
//     confidence: score(value?.confidence, 50),

//     notes:
//       typeof value?.notes === "string"
//         ? value.notes.trim()
//         : "",
//   };
// }

// // ============================================================
// // FINAL REPORT NORMALIZER
// // ============================================================

// function normalizeReport(value) {
//   return {
//     overall: score(value?.overall, 50),
//     technical: score(value?.technical, 50),
//     communication: score(value?.communication, 50),
//     confidence: score(value?.confidence, 50),
//     problemSolving: score(value?.problemSolving, 50),
//     coding: score(value?.coding, 0),

//     strengths: stringList(value?.strengths),
//     weaknesses: stringList(value?.weaknesses),
//     suggestions: stringList(value?.suggestions),

//     quotedMoments: Array.isArray(value?.quotedMoments)
//       ? value.quotedMoments.filter(
//           (item) =>
//             item &&
//             typeof item.quote === "string"
//         )
//       : [],

//     summary:
//       typeof value?.summary === "string"
//         ? value.summary.trim()
//         : "",
//   };
// }

// // ============================================================
// // AI SERVICE
// // ============================================================

// /**
//  * The rest of the application must ONLY talk to this facade.
//  *
//  * Business logic should never directly communicate with
//  * Ollama, Groq, or Gemini.
//  *
//  * Changing AI_PROVIDER therefore requires no changes
//  * elsewhere in the application.
//  */

// const aiService = {

//   // ----------------------------------------------------------
//   // CURRENT PROVIDER
//   // ----------------------------------------------------------

//   currentProvider: () => AI_PROVIDER,

//   // ----------------------------------------------------------
//   // EVALUATE SINGLE ANSWER
//   // ----------------------------------------------------------

//   async evaluateAnswer({
//     interview,
//     question,
//     answer,
//   }) {
//     const prompt = buildEvaluationPrompt({
//       interview,
//       question,
//       answer,
//     });

//     const provider = getProvider();

//     const text = await provider.complete([
//       {
//         role: "user",
//         content: prompt,
//       },
//     ]);

//     return normalizeEvaluation(
//       safeParseJSON(text, {
//         correctness: 50,
//         clarity: 50,
//         confidence: 50,
//         notes:
//           "Automated evaluation unavailable - default score applied.",
//       })
//     );
//   },

//   // ----------------------------------------------------------
//   // GENERATE SHORT FEEDBACK
//   // ----------------------------------------------------------

//   async generateFeedback({
//     interview,
//     transcript,
//   }) {
//     const provider = getProvider();

//     const systemPrompt = `
// You are an interviewer for a ${interview.category} interview.

// Give one short reaction to the candidate's last answer
// before the next question is asked.

// Keep the response to 1-2 sentences.
// Do not ask multiple questions.
// Do not provide a long explanation.
// `;

//     const messages = [
//       {
//         role: "system",
//         content: systemPrompt,
//       },

//       ...transcript.map((t) => ({
//         role:
//           t.role === "ai"
//             ? "assistant"
//             : "user",

//         content: t.content,
//       })),
//     ];

//     return provider.complete(messages);
//   },

//   // ----------------------------------------------------------
//   // GENERATE FINAL REPORT
//   // ----------------------------------------------------------

//   async generateFinalReport({
//     interview,
//     transcript,
//     responses,
//   }) {
//     const prompt = buildFinalReportPrompt({
//       interview,
//       transcript,
//       responses,
//     });

//     const provider = getProvider();

//     const text = await provider.complete([
//       {
//         role: "user",
//         content: prompt,
//       },
//     ]);

//     return normalizeReport(
//       safeParseJSON(text, {
//         overall: 50,
//         technical: 50,
//         communication: 50,
//         confidence: 50,
//         problemSolving: 50,
//         coding: 0,

//         strengths: [],
//         weaknesses: [],

//         suggestions: [
//           "Automated report generation failed - please retry.",
//         ],

//         quotedMoments: [],

//         summary:
//           "Report could not be generated by the AI provider.",
//       })
//     );
//   },

//   // ----------------------------------------------------------
//   // PLACEMENT ANALYSIS
//   // ----------------------------------------------------------

//   async generatePlacementAnalysis({
//     readinessScore,
//     readinessLevel,
//     categoryReports,
//   }) {
//     const prompt = buildPlacementAnalysisPrompt({
//       readinessScore,
//       readinessLevel,
//       categoryReports,
//     });

//     const provider = getProvider();

//     const text = await provider.complete([
//       {
//         role: "user",
//         content: prompt,
//       },
//     ]);

//     return safeParseJSON(text, {
//       strengths: [],
//       weaknesses: [],
//       consistentSkills: [],
//       improvementSkills: [],

//       improvementPriority: [
//         "Automated placement analysis unavailable - please retry.",
//       ],

//       careerSummary:
//         "AI analysis could not be generated.",

//       finalRecommendation:
//         "Complete more interviews and retry.",
//     });
//   },

//   // ----------------------------------------------------------
//   // RESUME PARSING
//   // ----------------------------------------------------------

//   async parseResume({
//     resumeText,
//   }) {
//     const prompt = buildResumeParsePrompt({
//       resumeText,
//     });

//     const provider = getProvider();

//     const text = await provider.complete([
//       {
//         role: "user",
//         content: prompt,
//       },
//     ]);

//     return safeParseJSON(text, {
//       skills: [],
//       programmingLanguages: [],
//       frameworks: [],
//       databases: [],
//       coreCsSubjects: [],
//       projects: [],
//       experience: [],
//       certifications: [],
//     });
//   },

//   // ----------------------------------------------------------
//   // RESUME VS INTERVIEW ANALYSIS
//   // ----------------------------------------------------------

//   async analyzeResumeVsInterview({
//     resumeProfile,
//     categoryReports,
//   }) {
//     const prompt = buildResumeVsInterviewPrompt({
//       resumeProfile,
//       categoryReports,
//     });

//     const provider = getProvider();

//     const text = await provider.complete([
//       {
//         role: "user",
//         content: prompt,
//       },
//     ]);

//     return safeParseJSON(text, {
//       matchScore: 0,

//       verifiedSkills: [],
//       unverifiedSkills: [],
//       improvementSkills: [],
//       missingAreas: [],

//       suggestions: [
//         "Automated resume analysis unavailable - please retry.",
//       ],

//       summary:
//         "AI analysis could not be generated.",
//     });
//   },
// };

// module.exports = aiService;

const { AI_PROVIDER } = require("../../config/env");

const ollamaProvider = require("./ollamaProvider");
const groqProvider = require("./groqProvider");
const geminiProvider = require("./geminiProvider");

const {
  buildEvaluationPrompt,
  buildFinalReportPrompt,
  buildPlacementAnalysisPrompt,
  buildResumeParsePrompt,
  buildResumeVsInterviewPrompt,
} = require("../../prompts/promptBuilder");

// ============================================================
// AI PROVIDERS
// ============================================================

const PROVIDERS = {
  ollama: ollamaProvider,
  groq: groqProvider,
  gemini: geminiProvider,
};

// ============================================================
// GET ACTIVE PROVIDER
// ============================================================

function getProvider() {
  const provider = PROVIDERS[AI_PROVIDER];

  if (!provider) {
    throw new Error(
      `Unknown AI_PROVIDER "${AI_PROVIDER}". Use ollama | groq | gemini.`
    );
  }

  return provider;
}

// ============================================================
// JSON HELPERS
// ============================================================

function stripJsonFences(text) {
  if (typeof text !== "string") {
    return "";
  }

  return text
    .replace(/```json/gi, "")
    .replace(/```/g, "")
    .trim();
}

function safeParseJSON(text, fallback) {
  try {
    return JSON.parse(stripJsonFences(text));
  } catch {
    return fallback;
  }
}

// ============================================================
// NORMALIZATION HELPERS
// ============================================================

function score(value, fallback = 0) {
  const numeric = Number(value);

  return Number.isFinite(numeric)
    ? Math.max(0, Math.min(100, Math.round(numeric)))
    : fallback;
}

function stringList(value) {
  return Array.isArray(value)
    ? value
        .filter((item) => typeof item === "string")
        .map((item) => item.trim())
        .filter(Boolean)
    : [];
}

// ============================================================
// EVALUATION NORMALIZER
// ============================================================

function normalizeEvaluation(value) {
  return {
    correctness: score(value?.correctness, 50),
    clarity: score(value?.clarity, 50),
    confidence: score(value?.confidence, 50),

    notes:
      typeof value?.notes === "string"
        ? value.notes.trim()
        : "",
  };
}

// ============================================================
// FINAL REPORT NORMALIZER
// ============================================================

function normalizeReport(value) {
  return {
    overall: score(value?.overall, 50),
    technical: score(value?.technical, 50),
    communication: score(value?.communication, 50),
    confidence: score(value?.confidence, 50),
    problemSolving: score(value?.problemSolving, 50),
    coding: score(value?.coding, 0),

    strengths: stringList(value?.strengths),
    weaknesses: stringList(value?.weaknesses),
    suggestions: stringList(value?.suggestions),

    quotedMoments: Array.isArray(value?.quotedMoments)
      ? value.quotedMoments.filter(
          (item) =>
            item &&
            typeof item.quote === "string"
        )
      : [],

    summary:
      typeof value?.summary === "string"
        ? value.summary.trim()
        : "",
  };
}

// ============================================================
// AI SERVICE
// ============================================================

/**
 * The rest of the application must ONLY talk to this facade.
 *
 * Business logic should never directly communicate with
 * Ollama, Groq, or Gemini.
 *
 * Changing AI_PROVIDER therefore requires no changes
 * elsewhere in the application.
 */

const aiService = {

  // ==========================================================
  // CURRENT PROVIDER
  // ==========================================================

  currentProvider: () => AI_PROVIDER,

  // ==========================================================
  // EVALUATE SINGLE ANSWER
  // ==========================================================

  async evaluateAnswer({
    interview,
    question,
    answer,
  }) {
    const prompt = buildEvaluationPrompt({
      interview,
      question,
      answer,
    });

    const provider = getProvider();

    const text = await provider.complete([
      {
        role: "user",
        content: prompt,
      },
    ]);

    return normalizeEvaluation(
      safeParseJSON(text, {
        correctness: 50,
        clarity: 50,
        confidence: 50,
        notes:
          "Automated evaluation unavailable - default score applied.",
      })
    );
  },

  // ==========================================================
  // GENERATE SHORT FEEDBACK
  // ==========================================================

  async generateFeedback({
    interview,
    transcript,
  }) {
    const provider = getProvider();

    const systemPrompt = `
You are an interviewer for a ${interview.category} interview.

Give one short reaction to the candidate's last answer
before the next question is asked.

Keep the response to 1-2 sentences.
Do not ask multiple questions.
Do not provide a long explanation.
`;

    const messages = [
      {
        role: "system",
        content: systemPrompt,
      },

      ...transcript.map((t) => ({
        role:
          t.role === "ai"
            ? "assistant"
            : "user",
        content: t.content,
      })),
    ];

    return provider.complete(messages);
  },

  // ==========================================================
  // GENERATE FINAL REPORT
  // ==========================================================

  async generateFinalReport({
    interview,
    transcript,
    responses,
  }) {
    const prompt = buildFinalReportPrompt({
      interview,
      transcript,
      responses,
    });

    const provider = getProvider();

    const text = await provider.complete([
      {
        role: "user",
        content: prompt,
      },
    ]);

    return normalizeReport(
      safeParseJSON(text, {
        overall: 50,
        technical: 50,
        communication: 50,
        confidence: 50,
        problemSolving: 50,
        coding: 0,

        strengths: [],
        weaknesses: [],

        suggestions: [
          "Automated report generation failed - please retry.",
        ],

        quotedMoments: [],

        summary:
          "Report could not be generated by the AI provider.",
      })
    );
  },

  // ==========================================================
  // GENERATE PLACEMENT ANALYSIS
  // ==========================================================

  async generatePlacementAnalysis({
    readinessScore,
    readinessLevel,
    categoryReports,
  }) {
    const prompt = buildPlacementAnalysisPrompt({
      readinessScore,
      readinessLevel,
      categoryReports,
    });

    const provider = getProvider();

    const text = await provider.complete([
      {
        role: "user",
        content: prompt,
      },
    ]);

    return safeParseJSON(text, {
      strengths: [],
      weaknesses: [],
      consistentSkills: [],
      improvementSkills: [],

      improvementPriority: [
        "Automated placement analysis unavailable - please retry.",
      ],

      careerSummary:
        "AI analysis could not be generated.",

      finalRecommendation:
        "Complete more interviews and retry.",
    });
  },

  // ==========================================================
  // PARSE RESUME
  // ==========================================================

  async parseResume({
    resumeText,
  }) {
    const prompt = buildResumeParsePrompt({
      resumeText,
    });

    const provider = getProvider();

    const text = await provider.complete([
      {
        role: "user",
        content: prompt,
      },
    ]);

    return safeParseJSON(text, {
      skills: [],
      programmingLanguages: [],
      frameworks: [],
      databases: [],
      coreCsSubjects: [],
      projects: [],
      experience: [],
      certifications: [],
    });
  },

  // ==========================================================
  // RESUME VS INTERVIEW ANALYSIS
  // ==========================================================

  async analyzeResumeVsInterview({
    resumeProfile,
    categoryReports,
  }) {
    const prompt = buildResumeVsInterviewPrompt({
      resumeProfile,
      categoryReports,
    });

    const provider = getProvider();

    const text = await provider.complete([
      {
        role: "user",
        content: prompt,
      },
    ]);

    return safeParseJSON(text, {
      matchScore: 0,

      verifiedSkills: [],
      unverifiedSkills: [],
      improvementSkills: [],
      missingAreas: [],

      suggestions: [
        "Automated resume analysis unavailable - please retry.",
      ],

      summary:
        "AI analysis could not be generated.",
    });
  },
};

// ============================================================
// EXPORT
// ============================================================

module.exports = aiService;

