// Curated placement-interview question bank. Each of the application's five
// existing categories has 20 questions, which covers the API's 20-question
// interview limit without repeating a question in a normal session.
const questionBankSeed = [
  // HR / Behavioral
  ["hr", "easy", "Introduction", "Tell me about yourself and connect your background to the role you are applying for."],
  ["hr", "easy", "Motivation", "Why are you interested in this company and this role?"],
  ["hr", "easy", "Strengths", "What are your strongest professional skills, and how have you demonstrated them?"],
  ["hr", "easy", "Weaknesses", "What is one area you are actively improving, and what are you doing about it?"],
  ["hr", "easy", "Career goals", "Where would you like your career to be in the next three to five years?"],
  ["hr", "medium", "Teamwork", "Describe a time you worked with people who had different opinions. How did the team reach a decision?"],
  ["hr", "medium", "Conflict", "Tell me about a conflict with a teammate or stakeholder. What did you do, and what was the outcome?"],
  ["hr", "medium", "Ownership", "Give an example of a time you took ownership of a problem that was not formally assigned to you."],
  ["hr", "medium", "Failure", "Describe a setback or failure. What did you learn, and how did you apply that learning later?"],
  ["hr", "medium", "Feedback", "Tell me about constructive feedback you received and how it changed your approach."],
  ["hr", "medium", "Prioritization", "Describe a situation where you had several urgent tasks. How did you prioritize and communicate your choices?"],
  ["hr", "medium", "Learning", "Tell me about a new skill you had to learn quickly. How did you plan and measure your progress?"],
  ["hr", "medium", "Communication", "Explain a time you had to communicate a technical or complex idea to a non-technical audience."],
  ["hr", "medium", "Leadership", "Describe a time you influenced a team without having formal authority."],
  ["hr", "medium", "Adaptability", "Tell me about a time a project requirement changed significantly. How did you adapt?"],
  ["hr", "hard", "Ethics", "Describe a time you noticed a risk or ethical concern. How did you raise it and what happened?"],
  ["hr", "hard", "Ambiguity", "Tell me about a time you had to make progress with incomplete information. What assumptions did you make?"],
  ["hr", "hard", "Stakeholders", "Describe how you handled conflicting expectations from two important stakeholders."],
  ["hr", "hard", "Resilience", "Share an example of delivering under pressure while protecting quality and team well-being."],
  ["hr", "hard", "Culture", "What kind of team environment helps you do your best work, and how do you contribute to it?"],

  // Data Structures & Algorithms
  ["dsa", "easy", "Arrays", "Given an array of integers and a target, how would you find two distinct elements whose sum equals the target? State the time and space complexity."],
  ["dsa", "easy", "Strings", "How would you determine whether a string is a palindrome while ignoring case and non-alphanumeric characters?"],
  ["dsa", "easy", "Hashing", "How would you find the first non-repeating character in a string, and why is a hash map useful?"],
  ["dsa", "easy", "Linked Lists", "How would you detect a cycle in a singly linked list? Explain the reasoning behind your approach."],
  ["dsa", "easy", "Stacks", "How would you validate whether parentheses in an expression are balanced?"],
  ["dsa", "medium", "Sliding Window", "Given a string, how would you find the length of its longest substring without repeating characters?"],
  ["dsa", "medium", "Binary Search", "How would you search for a target in a rotated sorted array, and what invariant would you maintain?"],
  ["dsa", "medium", "Trees", "How would you find the lowest common ancestor of two nodes in a binary tree?"],
  ["dsa", "medium", "BST", "How would you validate that a binary tree is a valid binary search tree?"],
  ["dsa", "medium", "Heaps", "How would you find the kth largest element in a large unsorted array, and what trade-offs are involved?"],
  ["dsa", "medium", "Graphs", "How would you determine whether a graph is bipartite using BFS or DFS?"],
  ["dsa", "medium", "Intervals", "How would you merge overlapping intervals after sorting them?"],
  ["dsa", "medium", "Dynamic Programming", "How would you compute the minimum number of coins needed to make an amount, and what is the dynamic-programming state?"],
  ["dsa", "medium", "Recursion", "How would you generate all subsets of a set of distinct integers? Explain the recursion tree."],
  ["dsa", "medium", "Queues", "How would you implement a queue using two stacks, and how do you achieve amortized O(1) operations?"],
  ["dsa", "hard", "Graphs", "How would you find the shortest path in a weighted graph with non-negative edges, and when would your approach not work?"],
  ["dsa", "hard", "Dynamic Programming", "How would you find the longest increasing subsequence in O(n log n) time? Explain the key data structure."],
  ["dsa", "hard", "Backtracking", "How would you solve the N-Queens problem, and what pruning decisions make the search practical?"],
  ["dsa", "hard", "Tries", "Design an autocomplete structure that returns words by prefix. What operations and complexities would it support?"],
  ["dsa", "hard", "Monotonic Stack", "How would you solve the largest rectangle in a histogram problem using a monotonic stack?"],

  // Core Computer Science
  ["core-cs", "easy", "OOP", "Explain encapsulation, inheritance, polymorphism, and abstraction with a practical example."],
  ["core-cs", "easy", "DBMS", "What is the difference between a primary key, a candidate key, and a foreign key?"],
  ["core-cs", "easy", "SQL", "What is the difference between an INNER JOIN and a LEFT JOIN? Give an example use case for each."],
  ["core-cs", "easy", "Operating Systems", "What is the difference between a process and a thread?"],
  ["core-cs", "easy", "Networks", "Walk through what happens from entering a URL in a browser until a web page begins to load."],
  ["core-cs", "medium", "Normalization", "Explain first, second, and third normal form. When might denormalization be justified?"],
  ["core-cs", "medium", "Indexes", "How does a database index improve query performance, and what are the write-time costs?"],
  ["core-cs", "medium", "Transactions", "What are the ACID properties of transactions? Give an example of why atomicity matters."],
  ["core-cs", "medium", "Deadlocks", "What four conditions are necessary for deadlock, and how can an operating system prevent or recover from it?"],
  ["core-cs", "medium", "Memory", "Compare paging and segmentation. What problem does virtual memory solve?"],
  ["core-cs", "medium", "Scheduling", "Compare FCFS, SJF, Round Robin, and priority scheduling. When is Round Robin useful?"],
  ["core-cs", "medium", "Concurrency", "What is a race condition, and how can locks or atomic operations prevent it?"],
  ["core-cs", "medium", "Networking", "Compare TCP and UDP and describe a situation where UDP is the better choice."],
  ["core-cs", "medium", "HTTP", "What is the difference between HTTP methods PUT, PATCH, and POST in a RESTful API?"],
  ["core-cs", "medium", "Caching", "What is cache invalidation, and which strategies can keep cached data consistent?"],
  ["core-cs", "hard", "Isolation", "Explain dirty reads, non-repeatable reads, and phantom reads. How do transaction isolation levels address them?"],
  ["core-cs", "hard", "Distributed Systems", "Explain the CAP theorem and how it affects a distributed database design decision."],
  ["core-cs", "hard", "Memory", "Compare stack and heap memory allocation. What kinds of bugs can arise from each?"],
  ["core-cs", "hard", "Networking", "Explain the TCP three-way handshake and why sequence numbers are needed."],
  ["core-cs", "hard", "Synchronization", "What is the difference between a mutex, semaphore, and monitor? When would you choose each?"],

  // Web Development
  ["web-dev", "easy", "HTML", "What is semantic HTML, and how does it improve accessibility and maintainability?"],
  ["web-dev", "easy", "CSS", "Explain the CSS box model and the effect of box-sizing: border-box."],
  ["web-dev", "easy", "JavaScript", "What is the difference between var, let, and const, and how does scope differ among them?"],
  ["web-dev", "easy", "JavaScript", "Explain event bubbling and event delegation with an example."],
  ["web-dev", "easy", "React", "What is the difference between props and state in React?"],
  ["web-dev", "medium", "JavaScript", "Explain the JavaScript event loop, including the call stack, task queue, and microtask queue."],
  ["web-dev", "medium", "React", "When would you use useEffect, and what common dependency-array bug should you avoid?"],
  ["web-dev", "medium", "React", "How would you prevent unnecessary React component re-renders in a large list?"],
  ["web-dev", "medium", "Node.js", "How does Node.js handle concurrent I/O despite JavaScript being single-threaded?"],
  ["web-dev", "medium", "Express", "How would you structure Express middleware for authentication, validation, and centralized error handling?"],
  ["web-dev", "medium", "REST APIs", "How would you design pagination for an API that serves a large collection?"],
  ["web-dev", "medium", "Authentication", "Compare session-based authentication with JWT-based authentication, including their security trade-offs."],
  ["web-dev", "medium", "MongoDB", "When would you embed documents in MongoDB, and when would you use references?"],
  ["web-dev", "medium", "TypeScript", "How do TypeScript interfaces and types differ, and how do they help a frontend codebase?"],
  ["web-dev", "medium", "Security", "How would you protect a web application against XSS, CSRF, and injection attacks?"],
  ["web-dev", "hard", "Performance", "How would you investigate and improve a slow React page that renders a large amount of data?"],
  ["web-dev", "hard", "Caching", "Describe an HTTP caching strategy for a public API and explain cache-control directives you would use."],
  ["web-dev", "hard", "Reliability", "How would you make an API endpoint safe to retry without creating duplicate records?"],
  ["web-dev", "hard", "Testing", "Describe a practical testing strategy across unit, integration, and end-to-end tests for a web application."],
  ["web-dev", "hard", "Deployment", "How would you design a zero-downtime deployment process for a web application?"],

  // System Design
  ["system-design", "easy", "Requirements", "How would you begin designing a URL shortener? What functional and non-functional requirements would you clarify first?"],
  ["system-design", "easy", "Load Balancing", "What does a load balancer do, and what are common load-balancing algorithms?"],
  ["system-design", "easy", "Caching", "Where can caching be introduced in a web system, and what data is a good caching candidate?"],
  ["system-design", "easy", "Databases", "How would you choose between a relational database and a document database for a new product?"],
  ["system-design", "easy", "APIs", "What makes an API design clear, versionable, and easy for clients to consume?"],
  ["system-design", "medium", "Rate Limiting", "Design a rate limiter for a public API. Which algorithm would you use and where would you enforce it?"],
  ["system-design", "medium", "Queues", "When would you introduce a message queue, and how would you handle retries and failed messages?"],
  ["system-design", "medium", "File Storage", "Design a service for users to upload and retrieve large files reliably."],
  ["system-design", "medium", "Notifications", "Design a notification system that can send email, push, and in-app messages at scale."],
  ["system-design", "medium", "Search", "Design a product search feature. How would you keep the search index synchronized with the source data?"],
  ["system-design", "medium", "Observability", "What metrics, logs, and traces would you add to diagnose latency and errors in a distributed service?"],
  ["system-design", "medium", "Authentication", "Design authentication and authorization for a multi-tenant SaaS application."],
  ["system-design", "medium", "CDN", "How does a CDN reduce latency, and how would you handle cache invalidation for changing content?"],
  ["system-design", "medium", "Scalability", "How would you scale a read-heavy service whose database is becoming a bottleneck?"],
  ["system-design", "medium", "Consistency", "How would you decide whether a feature needs strong consistency or can tolerate eventual consistency?"],
  ["system-design", "hard", "News Feed", "Design a social-media news feed. Compare fan-out on write and fan-out on read."],
  ["system-design", "hard", "Chat", "Design a real-time chat system that supports message ordering, delivery status, and offline users."],
  ["system-design", "hard", "Payments", "Design a payment-processing workflow that prevents double charges and provides an auditable record."],
  ["system-design", "hard", "Distributed Cache", "Design a distributed cache and explain eviction, replication, and cache-stampede mitigation."],
  ["system-design", "hard", "Availability", "Design a highly available service across multiple regions. How would you handle failover and data replication?"],
].map(([category, difficulty, topic, text]) => ({ category, difficulty, topic, text, active: true }));

module.exports = { questionBankSeed };
