module.exports = {
  hr: [
    "Tell me about yourself",
    "Why do you want to join this company",
    "Conflict resolution",
    "Strengths and weaknesses",
    "Career goals",
  ],
  dsa: [
    "Arrays",
    "Strings",
    "Linked List",
    "Stack",
    "Queue",
    "Trees",
    "BST",
    "Heap",
    "Trie",
    "Graph",
    "Dynamic Programming",
    "Recursion",
    "Greedy",
    "Backtracking",
    "Sliding Window",
    "Hashing",
  ],
  "core-cs": [
    "DBMS",
    "Operating System",
    "Computer Networks",
    "OOP",
    "SQL",
    "Transactions",
    "Normalization",
    "Deadlocks",
    "Paging",
    "Scheduling",
    "Indexes",
    "Concurrency",
    "ACID",
    "Locks",
  ],
  "web-dev": [
    "HTML",
    "CSS",
    "JavaScript",
    "TypeScript",
    "React",
    "Node.js",
    "Express.js",
    "MongoDB",
    "JWT",
    "REST APIs",
    "Git",
    "Tailwind CSS",
    "Authentication",
    "Authorization",
  ],
  "system-design": [
    "Caching",
    "Database Design",
    "Authentication",
    "Authorization",
    "Load Balancer",
    "Microservices",
    "Rate Limiting",
    "Docker",
    "CI/CD",
    "Scalability",
    "API Design",
    "Queues",
    "CDN",
  ],
};
